version: '3'
services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: "netbox-virtual-circuit-plugin/netbox:master-py3.8"
    command: sh -c "/opt/netbox/entrypoint.sh"
    ports:
    - "8000:8000"
    depends_on:
    - postgres
    - redis
    env_file:
    - docker/dev.env
    user: '101'
    volumes:
    - ./docker/configuration.py:/opt/netbox/netbox/netbox/configuration.py
    tty: true

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: "netbox-virtual-circuit-plugin/netbox:master-py3.8"
    command: sh -c "python manage.py rqworker"
    depends_on:
    - netbox
    env_file:
    - docker/dev.env
    user: '101'
    volumes:
    - ./docker/configuration.py:/opt/netbox/netbox/netbox/configuration.py
    tty: true

  postgres:
    image: postgres:12
    env_file: docker/dev.env
    volumes:
    - pgdata_netbox_virtual_circuit_plugin:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    command:
    - sh
    - -c  # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: docker/dev.env

volumes:
  pgdata_netbox_virtual_circuit_plugin:
    driver: local
